version: 2.1

executors:
  build_env:
    docker:
      - image: circleci/python:3.9.2

commands:
  build:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install mkdocs
            sudo pip install pymdown-extensions
            sudo pip install pygments
      - run:
          name: Install Theme
          command: |
            sudo python3 setup.py install
      - run:
          name: Build Site
          command: |
            mkdocs build --clean

jobs:
  build:
    executor: build_env
    steps:
      - build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
